<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Farah Syaima Raihanada">
<meta name="dcterms.date" content="2025-01-03">

<title>Pengaruh Partisipasi Indonesia dalam Pameran IFEX terhadap Jumlah Ekspor Furniture</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Pengaruh Partisipasi Indonesia dalam Pameran IFEX terhadap Jumlah Ekspor Furniture</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Farah Syaima Raihanada </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 3, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p><img src="poltekapp.jpg" class="img-fluid" alt="logo APP muncul secara random lalalala"></p>
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar belakang</h3>
<p>Industri furniture Indonesia, khususnya yang berbahan dasar rotan, memiliki potensi besar untuk berkembang dan bersaing di pasar internasional. Dengan kualitas dan desain yang khas, produk furniture Indonesia telah mendapatkan perhatian global. Sebagai sektor yang strategis, kontribusi industri ini terhadap perekonomian Indonesia terus meningkat, terutama dalam hal ekspor. Salah satu cara untuk mempromosikan produk Indonesia ke pasar internasional adalah melalui partisipasi dalam pameran dagang internasional, yang menjadi platform efektif untuk memperkenalkan produk dan memperluas jaringan bisnis.</p>
<p>Salah satu pameran terbesar yang memberikan dampak signifikan bagi industri furniture Indonesia adalah Indonesia International Furniture Expo (IFEX). Sejak pertama kali diselenggarakan pada tahun 2016, IFEX telah menjadi ajang penting bagi produsen furniture Indonesia untuk menampilkan produk mereka kepada pasar global. Keberhasilan IFEX terlihat dari peningkatan transaksi dan minat pembeli internasional terhadap produk-produk furniture Indonesia, khususnya yang menggunakan bahan dasar rotan. Pameran ini menjadi jembatan yang menghubungkan pengrajin lokal dengan pembeli global, memperkuat posisi Indonesia sebagai produsen furniture berkualitas tinggi.</p>
<p>Menurut laporan Direktorat Jenderal Pengembangan Ekspor Nasional (DJPEN) Kementerian Perdagangan, partisipasi Indonesia dalam pameran IFEX telah memberikan dampak positif terhadap nilai ekspor furniture, termasuk ke pasar ASEAN dan Republik Rakyat Tiongkok (RRT). Produk furniture rotan Indonesia semakin dikenal di dunia internasional, dan ini membuka peluang untuk meningkatkan pangsa pasar serta memperkuat daya saing produk Indonesia di pasar global.</p>
<p>Peningkatan ekspor furniture Indonesia melalui pameran IFEX ini mencerminkan pentingnya strategi promosi yang tepat guna mendukung pertumbuhan sektor ekspor. Dengan adanya pameran seperti IFEX, Indonesia dapat memperkenalkan produk-produk unggulannya kepada dunia, meningkatkan transaksi bisnis, dan menjalin kemitraan strategis yang berkelanjutan. Oleh karena itu, penelitian mengenai pengaruh partisipasi Indonesia dalam pameran IFEX terhadap jumlah ekspor furniture Indonesia sangat relevan untuk memberikan gambaran tentang sejauh mana pameran ini berkontribusi dalam meningkatkan kinerja ekspor, serta untuk merumuskan rekomendasi kebijakan bagi pengembangan sektor ekspor furniture Indonesia ke depannya.</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang lingkup</h3>
<p>Ruang lingkup penelitian ini fokus pada partisipasi Indonesia dalam pameran IFEX dari tahun 2019 hingga 2023, serta dampaknya terhadap jumlah ekspor furniture dalam periode tersebut. Batasan waktu yang diambil adalah 2014-2023 dan topik yang dibahas berkisar seputar efek partisipasi pameran internasional terhadap kinerja ekspor furniture.</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan masalah</h3>
<p>Rumusan masalah dalam penelitian ini adalah sebagai berikut:</p>
<ol type="1">
<li>Apakah terdapat hubungan signifikan antara partisipasi Indonesia di IFEX dengan jumlah ekspor furniture?</li>
<li>Berapa besar pengaruh partisipasi di IFEX terhadap volume ekspor furniture?</li>
<li>Faktor apa saja yang mempengaruhi jumlah ekspor furniture selain partisipasi di IFEX?</li>
</ol>
</section>
<section id="tujuan-dan-manfaat-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-dan-manfaat-penelitian"><span class="header-section-number">1.4</span> Tujuan dan manfaat penelitian</h3>
<p>Tujuan penelitian ini adalah:</p>
<ol type="1">
<li>Menganalisis pengaruh partisipasi Indonesia di IFEX terhadap jumlah ekspor furniture.</li>
<li>Memberikan informasi yang dapat dimanfaatkan oleh pengusaha furniture dan pihak terkait dalam mengambil keputusan pemasaran.</li>
</ol>
<p>Manfaat penelitian ini diharapkan dapat dirasakan oleh pengusaha furniture, pemerintah, serta akademisi untuk memahami lebih dalam mengenai peran pameran dalam meningkatkan ekspor.</p>
</section>
<section id="package" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="package"><span class="header-section-number">1.5</span> Package</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#/warning:false</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co">#/echo:true</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">'tidyverse'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi pustaka</h2>
<p>Studi Pustaka ini mencakup teori-teori mengenai ekspor dan dampaknya terhadap PDB :</p>
<section id="ekspor" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="ekspor"><span class="header-section-number">2.1</span> Ekspor</h3>
<p>Ekspor merupakan salah satu aktivitas perdagangan internasional di mana barang atau jasa dikirim dari satu negara ke negara lain untuk memenuhi kebutuhan pasar global dan mendapatkan devisa. Menurut Lipsey (1995), ekspor dapat didefinisikan sebagai total penjualan barang yang diproduksi suatu negara yang diperdagangkan ke negara lain dengan tujuan meningkatkan penerimaan nasional. Dalam konteks ini, ekspor tidak hanya menjadi sarana untuk meningkatkan pendapatan negara tetapi juga memperkuat posisi negara dalam rantai perdagangan global.</p>
<p>Di sektor furniture, ekspor memiliki peran strategis dalam mendukung pertumbuhan industri nasional. Produk furniture Indonesia yang berbasis kayu tropis sangat diminati di pasar internasional karena kualitas dan nilai estetikanya. Berdasarkan data Badan Pusat Statistik (2023), nilai ekspor furniture Indonesia mencapai USD 1,8 miliar, mencerminkan kontribusi signifikan sektor ini terhadap ekonomi nasional.</p>
</section>
<section id="pameran-dagang-internasional" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="pameran-dagang-internasional"><span class="header-section-number">2.2</span> Pameran Dagang Internasional</h3>
<p>Pameran dagang internasional merupakan salah satu sarana promosi yang efektif dalam meningkatkan eksposur produk di pasar global. Menurut Nugroho (2018), pameran internasional memberikan platform strategis bagi pelaku usaha untuk memamerkan produk mereka, menjalin kerja sama bisnis, dan memahami kebutuhan pasar. Indonesia International Furniture Expo (IFEX) adalah salah satu pameran dagang terbesar di Asia Tenggara yang fokus pada produk furniture.</p>
<p>IFEX tidak hanya memfasilitasi transaksi bisnis tetapi juga menjadi ajang untuk memperluas jaringan internasional. Pada IFEX 2022, nilai transaksi mencapai USD 650 juta, menunjukkan bahwa pameran ini memiliki peran signifikan dalam meningkatkan nilai ekspor furniture Indonesia. Selain itu, IFEX juga memberikan kesempatan bagi pengrajin lokal untuk memamerkan produk mereka kepada pembeli internasional, meningkatkan daya saing produk di pasar global.</p>
</section>
<section id="hubungan-ekspor-dan-pertumbuhan-ekonomi" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="hubungan-ekspor-dan-pertumbuhan-ekonomi"><span class="header-section-number">2.3</span> Hubungan Ekspor dan Pertumbuhan Ekonomi</h3>
<p>Ekspor memiliki hubungan erat dengan pertumbuhan ekonomi. Menurut Sukirno (2011), peningkatan ekspor dapat mendorong pertumbuhan Produk Domestik Bruto (PDB) melalui peningkatan pendapatan nasional. Dalam hal ini, kontribusi industri furniture terhadap PDB non-migas sebesar 1,3% pada tahun 2023 menunjukkan dampak signifikan sektor ini terhadap pertumbuhan ekonomi.</p>
<p>Teori ekonomi klasik menyatakan bahwa ekspor merupakan salah satu motor penggerak utama pertumbuhan ekonomi, terutama bagi negara berkembang seperti Indonesia. Partisipasi dalam pameran dagang seperti IFEX memungkinkan peningkatan volume dan nilai ekspor, yang pada akhirnya berkontribusi terhadap peningkatan pendapatan nasional.</p>
</section>
<section id="strategi-meningkatkan-ekspor-furniture" class="level3" data-number="2.4">
<h3 data-number="2.4" class="anchored" data-anchor-id="strategi-meningkatkan-ekspor-furniture"><span class="header-section-number">2.4</span> Strategi Meningkatkan Ekspor Furniture</h3>
<p>Dalam upaya meningkatkan ekspor furniture, pemerintah dan asosiasi seperti HIMKI (Himpunan Industri Mebel dan Kerajinan Indonesia) memainkan peran penting. Pemerintah telah memberikan berbagai insentif, termasuk kemudahan prosedur ekspor-impor dan insentif perpajakan, untuk mendukung daya saing industri furniture.</p>
<p>Selain itu, HIMKI mendorong inovasi produk yang mengedepankan nilai budaya dan keberlanjutan. Produk yang inovatif dan sesuai dengan tren pasar global memiliki daya tarik lebih besar di pasar internasional. Partisipasi dalam pameran IFEX juga menjadi salah satu strategi utama untuk memperkuat eksposur internasional dan memperluas jaringan bisnis.</p>
</section>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode penelitian</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<p>Berikut adalah data yang digunakan sebagai objek penelitian, data dibawah ini merupakan data nilai ekspor furniture Indonesia ke seluruh dunia dan GDP per Capita Indonesia dengan satuan USD.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Tahun</th>
<th>X (Nilai Ekspor Furniture)</th>
<th>Y (GDP Indonesia)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2014</td>
<td>$ 1902064117</td>
<td>$ 175980000000</td>
</tr>
<tr class="even">
<td>2015</td>
<td>$ 1817542455,34</td>
<td>$ 150366300000</td>
</tr>
<tr class="odd">
<td>2016</td>
<td>$ 1689165393,4</td>
<td>$ 145134000000</td>
</tr>
<tr class="even">
<td>2017</td>
<td>$ 1720494327,8</td>
<td>$ 168828200000</td>
</tr>
<tr class="odd">
<td>2018</td>
<td>$ 1797254672,63</td>
<td>$ 180012700000</td>
</tr>
<tr class="even">
<td>2019</td>
<td>$ 2064288757,96</td>
<td>$ 167683000000</td>
</tr>
<tr class="odd">
<td>2020</td>
<td>$ 2287497929,36</td>
<td>$ 163191800000</td>
</tr>
<tr class="even">
<td>2021</td>
<td>$ 3018254229,59</td>
<td>$ 231609500000</td>
</tr>
<tr class="odd">
<td>2022</td>
<td>$ 2935607412,31</td>
<td>$ 291904300000</td>
</tr>
<tr class="even">
<td>2023</td>
<td>$ 2286335102,91</td>
<td>$ 258774300000</td>
</tr>
</tbody>
</table>
<p>Penelitian ini menggunakan data sekunder dengan bentuk data&nbsp;<em>time series</em>&nbsp;2014-2023, data yang dipakai ialah data yang telah diolah dengan sumber UN Comtrade dan Badan Pusat Statistik Indonesia.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"D:/TA"</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>minita<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"DataFurniture.xlsx"</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>reg2<span class="ot">&lt;-</span><span class="fu">lm</span>(<span class="at">data =</span> minita,Y<span class="sc">~</span>X)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ X, data = minita)

Residuals:
       Min         1Q     Median         3Q        Max 
-4.133e+10 -1.771e+10 -3.458e+09  1.465e+10  5.435e+10 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept) 1.616e+10  4.785e+10   0.338  0.74424   
X           8.234e+01  2.174e+01   3.787  0.00534 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.158e+10 on 8 degrees of freedom
Multiple R-squared:  0.6419,    Adjusted R-squared:  0.5971 
F-statistic: 14.34 on 1 and 8 DF,  p-value: 0.005337</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>minita<span class="sc">$</span>m <span class="ot">&lt;-</span><span class="fu">resid</span>(reg2)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(minita<span class="sc">$</span>X,minita<span class="sc">$</span>m,<span class="at">ylab=</span><span class="st">"error"</span>,<span class="at">col=</span><span class="st">'yellow'</span>,<span class="at">pch=</span><span class="dv">16</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><em>Figure&nbsp;1: Plot pengaruh error terhadap nilai ekspor furniture</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>minita<span class="sc">$</span>m <span class="ot">&lt;-</span><span class="fu">resid</span>(reg2)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(minita<span class="sc">$</span>Y,minita<span class="sc">$</span>m,<span class="at">ylab=</span><span class="st">"error"</span>,<span class="at">col=</span><span class="st">'green'</span>,<span class="at">pch=</span><span class="dv">16</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><em>Figure&nbsp;2: Plot pengaruh error terhadap GDP Indonesia</em></p>
</section>
<section id="metode-analisis" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.2</span> Metode analisis</h3>
<p>Metode yang digunakan dalam penelitian ini adalah regresi univariat atau Ordinary Least Square (OLS) untuk menganalisis pengaruh partisipasi di IFEX berupa peningkatan nilai ekspor furniture (variabel independen, X) terhadap GDP Indonesia (variabel dependen, Y). Model yang digunakan adalah:<span class="math display">\[
y_{t}=\beta_0 + \beta_1 x_t+ϵ
\]</span> di mana <span class="math inline">\(y_t\)</span> adalah GDP dan <span class="math inline">\(x_t\)</span> adalah peningkatan nilai ekspor furniture.</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan masalah</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Variabel</th>
<th>Coefficient</th>
<th>Std.Error</th>
<th>T-Value</th>
<th>P-Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>16.160000000</td>
<td>4.785</td>
<td>0.338</td>
<td>0.744</td>
</tr>
<tr class="even">
<td>X</td>
<td>82.34</td>
<td>2.174</td>
<td>3.787</td>
<td>0.00534</td>
</tr>
<tr class="odd">
<td>R.squared</td>
<td>0.6419</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Adjusted R-Squared</td>
<td>0.5971</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Residual Std Error</td>
<td>3.1580000</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>F-statistic</td>
<td>14.34</td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>Model regresi multivariat dari output di atas adalah:</p>
<p><span class="math display">\[
y_{t}=(161e+10) + (82.34)X+ϵ
\]</span></p>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> Analisis masalah</h3>
<p>Hasil regresinya adalah</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>reg2<span class="ot">&lt;-</span><span class="fu">lm</span>(<span class="at">data =</span> minita,Y<span class="sc">~</span>X)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ X, data = minita)

Residuals:
       Min         1Q     Median         3Q        Max 
-4.133e+10 -1.771e+10 -3.458e+09  1.465e+10  5.435e+10 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept) 1.616e+10  4.785e+10   0.338  0.74424   
X           8.234e+01  2.174e+01   3.787  0.00534 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.158e+10 on 8 degrees of freedom
Multiple R-squared:  0.6419,    Adjusted R-squared:  0.5971 
F-statistic: 14.34 on 1 and 8 DF,  p-value: 0.005337</code></pre>
</div>
</div>
<p>X dan YYY. Meskipun model ini memberikan hasil yang signifikan secara statistik (baik untuk intercept maupun koefisien XXX), nilai&nbsp;<strong>R-squared</strong>&nbsp;yang relatif rendah (0.6419) menunjukkan bahwa model ini hanya dapat menjelaskan sebagian kecil dari variasi dalam YYY. Oleh karena itu, model ini mungkin perlu dikembangkan lebih lanjut dengan mempertimbangkan variabel lain atau menggunakan pendekatan yang lebih kompleks untuk memperbaiki akurasi prediksi.</p>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5</span> Kesimpulan</h2>
<p>Nilai koefisien X sebesar 82.34 menunjukkan bahwa setiap peningkatan sebesar 1 unit dalam ekspor furniture hasil dari partisipasi Indonesia dalam pameran IFEX akan meningkatkan GDP Indonesia sebesar 82.34 unit. Ini menunjukkan pengaruh positif yang signifikan (p value = 0,005). Secara keseluruhan signifikan tersebut berarti bahwa adanya peningkatan nilai ekspor furniture memiliki peran yang cukup penting dalam memengaruhi GDP Indonesia. Meskipun cukup tinggi, namun ada faktor lainnya. Variasi besar dalam residual (-4.133e+10) hingga (5.435e+10) menunjukkan adanya faktor eksternal lain yang tidak tercakup oleh model.</p>
<p>Partisipasi Indonesia dalam pameran IFEX yang meningkatkan nilai ekspor furnitur memiliki pengaruh positif yang signifikan terhadap GDP Indonesia. Hal ini menunjukkan bahwa peningkatan ekspor furnitur sebagai hasil dari promosi di IFEX dapat berkontribusi pada pertumbuhan ekonomi nasional. Dengan 64.19% variasi GDP yang dapat dijelaskan oleh nilai ekspor furnitur, peran industri furnitur cukup signifikan dalam mendukung perekonomian. Namun, sisanya menunjukkan pentingnya variabel lain, seperti sektor ekonomi lainnya, investasi, atau konsumsi domestik. Pemerintah dapat meningkatkan dukungan terhadap partisipasi dalam pameran internasional seperti IFEX untuk mendorong ekspor furnitur lebih lanjut. Hasil tersebut mendukung pentingnya pameran seperti IFEX sebagai platform untuk meningkatkan ekspor yang pada akhirnya berkontribusi terhadap pertumbuhan ekonomi nasional.</p>
</section>
<section id="referensi" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="referensi"><span class="header-section-number">6</span> Referensi</h2>
<p>HIMKI. (2023). Mendorong Ekspor Indonesia melalui Pameran Mebel dan Kerajinan Berkualitas Internasional. Retrieved from <a href="https://ifexindonesia.com/media/press-release/mendorong-ekspor-indonesia-melalui-pameran-mebel-dan-kerajinan-berkualitas-internasional-20240124141405" class="uri">https://ifexindonesia.com/media/press-release/mendorong-ekspor-indonesia-melalui-pameran-mebel-dan-kerajinan-berkualitas-internasional-20240124141405</a></p>
<p>Badan Pusat Statistik. (n.d.). <em>Ekspor Impor Indonesia</em>. <a href="https://www.bps.go.id/id/exim" class="uri">https://www.bps.go.id/id/exim</a></p>
<p>World Bank Indicator. <em>GDP Per Capita Indonesia Current $.</em> <a href="https://data.worldbank.org/indicator/NY.GDP.MKTP.CD?end=2019&amp;locations=ID&amp;start=2019&amp;view=bar" class="uri">https://data.worldbank.org/indicator/NY.GDP.MKTP.CD?end=2019&amp;locations=ID&amp;start=2019&amp;view=bar</a></p>
<p>UN Comtrade. <em>Export HS 94 from Indonesian to World</em>. <a href="https://comtradeplus.un.org/" class="uri">https://comtradeplus.un.org/</a></p>
<p>Elysi, M. G., &amp; Riptanti, E. W. (2018, March). The analysis of export commodity competitiveness in Central Java Province at period 2011-2015. In&nbsp;<em>IOP Conference Series: Earth and Environmental Science</em>&nbsp;(Vol. 142, No.&nbsp;1, p.&nbsp;012061). IOP Publishing. <a href="https://iopscience.iop.org/article/10.1088/1755-1315/142/1/012061/meta" class="uri">https://iopscience.iop.org/article/10.1088/1755-1315/142/1/012061/meta</a></p>
<p>Anwar, M. F., Harianto, H., &amp; Suharno, S. (2020). Dinamika Daya Saing Ekspor Furniture Rotan Indonesia Ke Negara Tujuan Eropa.&nbsp;<em>Jurnal Agribisnis Indonesia (Journal of Indonesian Agribusiness)</em>,&nbsp;<em>8</em>(2), 152-163. <a href="https://core.ac.uk/reader/389123750" class="uri">https://core.ac.uk/reader/389123750</a></p>
<p>Nisa, F. D. (2019). Analisis Faktor-Faktor yang Mempengaruhi Ekspor Furniture Rotan Indonesia.</p>
<p>Kasnelly, S. (2023). Pertumbuhan Ekonomi Indonesia ditinjau dari Produk Berbasis Ekspor.&nbsp;<em>Al-A’mal: Jurnal Manajemen Bisnis Syariah</em>,&nbsp;<em>3</em>(II). <a href="https://ejournal.an-nadwah.ac.id/index.php/Al-amal/article/view/569/450" class="uri">https://ejournal.an-nadwah.ac.id/index.php/Al-amal/article/view/569/450</a></p>
<p>Pamungkas, T., Aminudin, A., &amp; Saputri, F. S. (2024). Pameran Jepara International Furniture Buyer Weeks Untuk Meningkatkan Export Mebel di Jepara.&nbsp;<em>Hikmah Journal of Community Service</em>,&nbsp;<em>2</em>(4), 1-6. <a href="https://hijcoms.univ-alhikmahjepara.ac.id/index.php/hijcoms/article/view/32/48" class="uri">https://hijcoms.univ-alhikmahjepara.ac.id/index.php/hijcoms/article/view/32/48</a></p>
<p>KompasIndo. (2024). Indonesia International Furniture Expo (IFEX) 2024 - Pemanfaatan teknologi tingkatkan pertumbuhan industri furnitur. Retrieved from <a href="https://kompasindo.co.id/2024/02/indonesia-international-furniture-expo-ifex-2024-pemanfaatan-teknologi-tingkatkan-pertumbuhan-industri-furnitur/" class="uri">https://kompasindo.co.id/2024/02/indonesia-international-furniture-expo-ifex-2024-pemanfaatan-teknologi-tingkatkan-pertumbuhan-industri-furnitur/</a></p>
<p>InfoBrand. (2022). IFEX 2022: Dampak Positif Perkembangan Industri Furnitur bagi Lingkungan dan Penyerapan Tenaga Kerja. Retrieved from <a href="https://infobrand.id/ifex-2022dampak-positif-perkembangan-industri-furnitur-bagi-lingkungan-dan-penyerapan-tenaga-kerja.phtml" class="uri">https://infobrand.id/ifex-2022dampak-positif-perkembangan-industri-furnitur-bagi-lingkungan-dan-penyerapan-tenaga-kerja.phtml</a></p>
<p>DQLab. (2021). Metode Pengumpulan Data Sekunder dengan Studi Literatur. Retrieved from <a href="https://dqlab.id/metode-pengumpulan-data-sekunder-dengan-studi-literatur" class="uri">https://dqlab.id/metode-pengumpulan-data-sekunder-dengan-studi-literatur</a></p>
<p>Infobank News. (2024). Catatkan 13.000 Buyers Lebih, IFEX Hadirkan Harapan Bagi Ekonomi RI. Retrieved from <a href="https://infobanknews.com/catatkan-13-000-buyers-lebih-ifex-hadirkan-harapan-bagi-ekonomi-ri/" class="uri">https://infobanknews.com/catatkan-13-000-buyers-lebih-ifex-hadirkan-harapan-bagi-ekonomi-ri/</a></p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>